/* eslint-disable */
/**
 * Generated by `npx convex dev` (hand-written to match the template until a deployment is configured).
 * Re-run `npx convex dev` to regenerate.
 * @module
 */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as collections from "../collections.js";
import type * as farmers from "../farmers.js";
import type * as images from "../images.js";
import type * as orders from "../orders.js";
import type * as products from "../products.js";
import type * as seed from "../seed.js";

declare const fullApi: ApiFromModules<{
  collections: typeof collections;
  farmers: typeof farmers;
  images: typeof images;
  orders: typeof orders;
  products: typeof products;
  seed: typeof seed;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
