/* eslint-disable */
/**
 * Generated by `npx convex dev` (hand-written to match the template until a deployment is configured).
 * Re-run `npx convex dev` to regenerate.
 * @module
 */
import { anyApi } from "convex/server";
export const api = anyApi;
export const internal = anyApi;
